$pdf_mode=5;
$xelatex="xelatex -file-line-error --shell-escape -synctex=1 -interaction=nonstopmode %O %S";
# $pdf_previewer="xdg-open %S";
$pdf_previewer="zathura %S";
$preview_continuous_mode=1;
$out_dir="build"
